import ".././globals.css";

import Footer from "../components/frontend/Footer";
import Header from "../components/frontend/Header";
import { ToastContainer } from "react-toastify";
import UserChat from "../components/frontend/UserChat";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContactLayout({ children }) {
  return (
    <>
      <main>
        <Header />
        {children}
        <Footer />

        <ToastContainer position="bottom-right" />
      </main>

      <UserChat />
    </>
  );
}
