import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AuthProvider } from "./contexts/AuthContext";
import Header from "./components/frontend/Header";
import Footer from "./components/frontend/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <main>
            <Header />

            {children}
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
