import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AuthProvider } from "./contexts/AuthContext";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <main>
       

            {children}
         
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
